src/models.py
from mongoengine import Document, EmailField, StringField
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

class User(UserMixin, Document):
    email = EmailField(required=True)
    password_hash = StringField()

    @property
    def password(self):
        raise AttributeError("password unreadable")

    #can just set with User.password = password and it will be auto hashed
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(uid):
        return User.objects(id=uid).first()

src/forms.py
from wtforms import Form, BooleanField, StringField, PasswordField, validators

class RegistrationForm(Form):
    email = StringField('Email Address', [validators.Length(min=6, max=35)])
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')

src/forms/__init__.py
from .register import RegistrationForm

src/forms/register.py
from wtforms import Form, BooleanField, StringField, PasswordField, validators

class RegistrationForm(Form):
    email = StringField('Email Address', [validators.Length(min=6, max=35)])
    password = PasswordField('New Password')

src/__init__.py
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_login import LoginManager

#local config.py
from .config import config

db = MongoEngine()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
# login_manager.login_view = 'main.index'

#Factory Creation of App Allowing Ez calling of other config rules
def create_app(config_name):
    app = Flask(__name__)
    #app.config is a dictionary object used for flask as well as package config
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # from .api import api as api_blueprint
    # app.register_blueprint(api_blueprint, url_prefix='/api')

    return app

src/main/__init__.py
from .views import main

src/main/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user, login_user
from passlib.hash import pbkdf2_sha256

from ..models import User
from ..forms import RegistrationForm

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template("index.html")

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        form = RegistrationForm(request.form)
        if not form.validate():
            flash("Form validation fails")
            return render_template('register.html', form=form)
        passwordHash = pbkdf2_sha256.hash(form.password.data)
        user = User(form.email.data, passwordHash)
        user.save()
        login_user(user)
        flash('Im a flash: Thanks for registering')
        return redirect(url_for('main.index'))

    return render_template('register.html')

src/templates/index.html
{% extends "layout.html" %}
{% block title %} Homepage {% endblock %}

{% block body %}
  <h1>
    <marquee><a href={{ url_for('main.register') }}> I'm working! </a></marquee>
  </h1>

  {% if current_user.is_authenticated %}
    <h2> Current user is {{ current_user.email }}</h2>
  {% endif %}
{% endblock %}

src/templates/layout.html
<!doctype html>
<html>
    <head>
        {% block head %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
        {% endblock %}
        <title> {% block title %} {% endblock %}</title>
    </head>
    <body>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class=flashes>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      
      {% block body %}{% endblock %}
    </body>
</html>

src/templates/register.html
{% extends "layout.html" %}
{% block title %} Register {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}">
{% endblock %}

<!-- Could also render with the help of wtf_forms, but not super worth -->
{% block body %}
  <form action="#" method="post" enctype="application/x-www-form-urlencoded">
    <div>
      <label for="email">Email</label>
      <input type="email"  name="email" id="email" placeholder="someone@example.com"/>
    </div>
    <div>
      <label for="password" >Password</label>
      <input type="password" name="password" id="password" placeholder="**************">
    </div>
    <div>
      <label for="confirm">Confirm</label>
      <input type="password" name="confirm" id="confirm" placeholder="**************">
    </div>
    <div class="button">
      <button type="submit"> Ok </button>
    </div>
  </form>
{% endblock %}